### ISSUE TITLE
Error while running app

### ISSUE THREAD

**Issue by astraiophos** [hydroshare/tethysapp-hydroshare_gis#31]
![error on gis app](https://cloud.githubusercontent.com/assets/17853890/18183449/b0e7776e-7051-11e6-9756-59f9f3437556.PNG)

**Comment by astraiophos** [comment]
Just tried running this during class, thought this might be what caused my machine to not run properly, not sure if it's meaningful or not

**Comment by shawncrawley** [comment]
Thanks for pointing this out. The HydroShare resource you were attempting to view was created by the HydroShare GIS app itself (as authorized by Dan Ames). When it was first created it worked properly. However, recent updates to the app included major changes to how the app both creates and consumes these resources. Since the resource in question was created before these changes, it can no longer be properly consumed by HydroShare GIS. As a solution to this issue, I have asked Dan Ames that he delete the resource in question and then re-create it if desired. Once that has been done, and if you are also satisfied, then I will close this issue.

**Comment by astraiophos** [comment]
Sounds great Shawn, I'm satisfied, just thought I'd put that info up so you could see what was happening
On Sep 7, 2016 2:00 PM, shawncrawley notifications@github.com wrote:Thanks for pointing this out. The HydroShare resource you were attempting to view was created by the HydroShare GIS app itself (as authorized by Dan Ames). When it was first created it worked properly. However, recent updates to the app included major changes to how the app both creates and consumes these resources. Since the resource in question was created before these changes, it can no longer be properly consumed by HydroShare GIS. As a solution to this issue, I have asked Dan Ames that he delete the resource in question and then re-create it if desired. Once that has been done, and if you are also satisfied, then I will close this issue.
